# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath D:/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/CPU54/CPU54.cache/wt [current_project]
set_property parent.project_path D:/CPU54/CPU54.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/test.coe
add_files D:/EggDrop.coe
add_files -quiet d:/CPU54/CPU54.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files d:/CPU54/CPU54.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  D:/CPU54/CPU54.srcs/sources_1/new/CLZ.v
  D:/CPU54/CPU54.srcs/sources_1/new/Decoder.v
  D:/CPU54/CPU54.srcs/sources_1/new/Controler.v
  D:/CPU54/CPU54.srcs/sources_1/new/ALU.v
  D:/CPU54/CPU54.srcs/sources_1/new/regfile.v
  D:/CPU54/CPU54.srcs/sources_1/new/PC.v
  D:/CPU54/CPU54.srcs/sources_1/new/CP0.v
  D:/CPU54/CPU54.srcs/sources_1/new/MUL.v
  D:/CPU54/CPU54.srcs/sources_1/new/DIV.v
  D:/CPU54/CPU54.srcs/sources_1/new/MUX.v
  D:/CPU54/CPU54.srcs/sources_1/new/HI_LO.v
  D:/CPU54/CPU54.srcs/sources_1/new/seg7x16.v
  D:/CPU54/CPU54.srcs/sources_1/new/IMEM.v
  D:/CPU54/CPU54.srcs/sources_1/new/DMEM.v
  D:/CPU54/CPU54.srcs/sources_1/new/Divider.v
  D:/CPU54/CPU54.srcs/sources_1/new/cpu.v
  D:/CPU54/CPU54.srcs/sources_1/new/sccomp_dataflow.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/CPU54/CPU54.srcs/constrs_1/new/CPU.xdc
set_property used_in_implementation false [get_files D:/CPU54/CPU54.srcs/constrs_1/new/CPU.xdc]


synth_design -top sccomp_dataflow -part xc7a100tcsg324-1


write_checkpoint -force -noxdef sccomp_dataflow.dcp

catch { report_utilization -file sccomp_dataflow_utilization_synth.rpt -pb sccomp_dataflow_utilization_synth.pb }
